Add missing dependency on shell.filename_extended
Comby uses the Filename_extended module, but does not depend on any
packages which define that module. This causes a build failure on my
machine:

    File "lib/interactive/interactive.ml", line 255, characters 17-48:
    255 |       let path = Filename_extended.make_relative path in
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    Error: Unbound module Filename_extended

Fix the error by depending on required packages.